default:
  golem_name: spectrum.regression.testing
  golem_version: 0.0.0.9000
  app_prod: no
  orderly_task_name: run_aim_all_countries
production:
  app_prod: yes
dev:
  golem_wd: !expr golem::pkg_path()
